### ISSUE TITLE
Unable to turn throwIfNotFound off

### ISSUE THREAD

**Issue by sgdc3** [Drarig29/ts-json-db#1]
https://github.com/Drarig29/ts-json-db/blob/01f9f012dfdc3b1b5cb0adc43b7764a8d763f331/src/index.ts#L65
This line will always change 'false' values to 'true'

**Comment by Drarig29** [comment]
Oh lol, you're right.

**Comment by Drarig29** [comment]
You can use v2.0.5 :wink:
